name: yolocap-ggcnn
channels:
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - numpy
  - pandas
  - tensorflow
  - ipykernel
  - pip
  - pip:
    - configparser
    - torchsummary
    - pillow
    - albumentations
    - tqdm
